# Generated by Django 5.2.9 on 2026-01-14 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcontacts',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optional +).', regex='^\\+?[1-9]\\d{6,14}$')]),
        ),
    ]
